let token=localStorage.getItem('taskearn_token')||'', user=null, authMode='register', activeTask=null;
const $=s=>document.querySelector(s);
async function api(path, options={}){options.headers={...(options.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(path,options);const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function openAuth(mode='register'){authMode=mode;$('#authModal').classList.remove('hidden');renderAuth()}
function closeAuth(){$('#authModal').classList.add('hidden');$('#authError').textContent=''}
function toggleAuth(){openAuth(authMode==='register'?'login':'register')}
function renderAuth(){const reg=authMode==='register';$('#authEyebrow').textContent=reg?'GET STARTED':'WELCOME BACK';$('#authTitle').textContent=reg?'Create your TaskEarn account':'Log in to TaskEarn';$('#authHint').textContent=reg?'Choose Worker to earn or Client to post tasks.':'Use your TaskEarn account credentials.';$('#role').classList.toggle('hidden',!reg);$('#authAction').textContent=reg?'Create account':'Log in';$('#authSwitch').textContent=reg?'Already have an account? Log in':'Need an account? Sign up'}
async function authSubmit(){try{const email=$('#email').value.trim(),password=$('#password').value;const data=await api('/api/'+(authMode==='register'?'register':'login'),{method:'POST',body:JSON.stringify({email,password,role:$('#role').value})});token=data.token;user=data.user;localStorage.setItem('taskearn_token',token);closeAuth();await refreshUI();location.hash=user.role==='client'?'client':'tasks'}catch(e){$('#authError').textContent=e.message}}
$('#authAction').onclick=authSubmit;
async function logout(){try{await api('/api/logout',{method:'POST'})}catch(e){}token='';user=null;localStorage.removeItem('taskearn_token');await refreshUI();location.hash=''}
async function loadMe(){try{const d=await api('/api/me');user=d.user}catch(e){user=null;token='';localStorage.removeItem('taskearn_token')}}
function updateNav(){const logged=!!user;$('#authNav').textContent=logged?`${user.email} · ${user.role}`:'Sign up free';$('#authNav').onclick=()=>{if(!logged)return openAuth('register');const target=user.role==='client'?'#client':user.role==='admin'?'#admin':'#tasks';document.querySelector(target).scrollIntoView()};$('#logoutBtn').classList.toggle('hidden',!logged)}
function updateUser(){const bal=user?user.balance_cents:0;$('#balance').textContent='$'+(bal/100).toFixed(2);if(user&&user.role==='worker'){loadWorkerSummary()}updateNav()}
async function loadWorkerSummary(){if(!user||user.role!=='worker')return;try{const d=await api('/api/worker/summary');$('#balance').textContent='$'+(d.balance_cents/100).toFixed(2);$('#approved').textContent='$'+(d.approved_cents/100).toFixed(2);$('#pending').textContent='$'+(d.pending_cents/100).toFixed(2);$('#completed').textContent=d.completed_tasks}catch(e){}}
async function loadTasks(cat='all'){try{const d=await api('/api/tasks'+(cat==='all'?'':'?category='+encodeURIComponent(cat)));const ts=d.tasks;$('#taskGrid').innerHTML=ts.length?ts.map(t=>`<article class="task"><div><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.description)}</p><div class="task-meta"><span>${escapeHtml(t.category)} · ~${t.est_minutes} min</span><span>● ${t.taken?'Submitted':'Available'} · ${t.slots_left} left</span></div></div><div class="reward"><b>${t.reward}</b><small>per task</small><button ${t.taken?'disabled':''} onclick="startTask(${t.id})">${t.taken?'Done':'Start'}</button></div></article>`).join(''):'<p class="empty">No open tasks in this category.</p>';$('#heroTasks').innerHTML=ts.slice(0,4).map(t=>`<div class="task-mini"><div><b>${escapeHtml(t.title)}</b><small>${escapeHtml(t.category)} · ${t.est_minutes} min</small></div><strong>${t.reward}</strong></div>`).join('')}catch(e){$('#taskGrid').innerHTML='<p class="empty">Log in as a worker to start tasks.</p>'}}
async function startTask(id){if(!user){openAuth('login');return}if(user.role!=='worker'){alert('This account is not a worker account.');return}try{const d=await api('/api/tasks/start',{method:'POST',body:JSON.stringify({task_id:id})});activeTask=d.task;$('#taskTitle').textContent=activeTask.title;$('#taskDescription').textContent=activeTask.description;$('#taskReward').textContent='$'+(activeTask.reward_cents/100).toFixed(2)+' reward';$('#taskTime').textContent='~'+activeTask.est_minutes+' min';$('#taskSlots').textContent=(activeTask.quantity-activeTask.completed_count)+' slots left';$('#taskAnswer').value='';$('#taskError').textContent='';$('#taskModal').classList.remove('hidden')}catch(e){alert(e.message)}}
function closeTask(){$('#taskModal').classList.add('hidden')}
async function submitTask(){try{const answer=$('#taskAnswer').value.trim();if(!answer){$('#taskError').textContent='Please enter your completed work.';return}await api('/api/tasks/submit',{method:'POST',body:JSON.stringify({task_id:activeTask.id,answer})});closeTask();await loadTasks();alert('Submitted. Your work is now pending client review.')}catch(e){$('#taskError').textContent=e.message}}
async function loadClient(){if(!user||user.role!=='client'){return}try{const [o,t,s]=await Promise.all([api('/api/client/overview'),api('/api/client/tasks'),api('/api/client/submissions')]);$('#clientBalance').textContent='$'+(o.balance_cents/100).toFixed(2);$('#clientTasksCount').textContent=o.tasks;$('#clientOpen').textContent=o.open_tasks;$('#clientPending').textContent=o.pending_submissions;$('#subs').innerHTML=s.submissions.length?s.submissions.map(x=>`<div class="submission"><b>${escapeHtml(x.title)}</b><small>${escapeHtml(x.worker_email)} · ${x.reward} · ${x.status}</small><p>${escapeHtml(x.answer)}</p>${x.status==='pending'?`<div class="submission-actions"><button class="btn btn-primary" onclick="reviewSubmission(${x.id},'approve')">Approve</button><button class="btn btn-light" onclick="reviewSubmission(${x.id},'reject')">Reject</button></div>`:''}</div>`).join(''):'<p class="empty">No submissions yet.</p>';$('#clientTaskList').innerHTML=t.tasks.length?t.tasks.map(x=>`<div class="client-task-row"><div><b>${escapeHtml(x.title)}</b><small>${x.status} · ${x.completed_count}/${x.quantity} complete · ${x.slots_left} left</small></div><strong>${x.budget}</strong></div>`).join(''):'<p class="empty">No tasks yet.</p>'}catch(e){console.log(e)}}
async function addTestFunds(){
 try{
  const r=await api('/api/client/test-funds',{method:'POST',body:JSON.stringify({amount:10})});
  $('#clientBalance').textContent='$'+(r.balance_cents/100).toFixed(2);
  alert('Test funds added: $10. No real payment was processed.');
 }catch(e){alert(e.message)}
}
async function createClientTask(){try{const payload={title:$('#ctitle').value,description:$('#cdesc').value,category:$('#ccat').value,reward:$('#creward').value,est_minutes:$('#ctime').value,quantity:$('#cqty').value};const r=await api('/api/client/tasks',{method:'POST',body:JSON.stringify(payload)});$('#ctitle').value='';$('#cdesc').value='';$('#creward').value='';$('#clientError').textContent='';alert(`Task funded with $${(r.funded_cents/100).toFixed(2)}.`);await loadClient();await loadTasks()}catch(e){$('#clientError').textContent=e.message}}
async function reviewSubmission(id,decision){try{await api('/api/client/review',{method:'POST',body:JSON.stringify({submission_id:id,decision})});await loadClient();await loadTasks();alert('Submission '+decision+'d.')}catch(e){alert(e.message)}}
function updateBudget(){const r=parseFloat($('#creward').value||0),q=parseInt($('#cqty').value||0);$('#budgetNote').textContent='Estimated funding: $'+((r*q)||0).toFixed(2)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}

async function loadAdmin(){if(!user||user.role!=='admin')return;try{const [o,u,t,s,l]=await Promise.all([api('/api/admin/overview'),api('/api/admin/users'),api('/api/admin/tasks'),api('/api/admin/submissions'),api('/api/admin/ledger')]);$('#adminEmail').textContent=user.email;$('#adminUsers').textContent=o.users;$('#adminWorkers').textContent=o.workers;$('#adminClients').textContent=o.clients;$('#adminOpenTasks').textContent=o.open_tasks;$('#adminPending').textContent=o.pending_submissions;$('#adminCredited').textContent='$'+(o.credited_cents/100).toFixed(2);$('#adminUsersTable').innerHTML=u.users.map(x=>`<div class="admin-row"><div><b>${escapeHtml(x.email)}</b><small>${x.role} · ${x.balance} · ${x.is_active?'active':'disabled'}</small></div><button class="btn btn-light" onclick="adminUserAction(${x.id},${x.is_active?'\'disable\'':'\'enable\''})">${x.is_active?'Disable':'Enable'}</button></div>`).join('');$('#adminTasksTable').innerHTML=t.tasks.map(x=>`<div class="admin-row"><div><b>${escapeHtml(x.title)}</b><small>${escapeHtml(x.client_email)} · ${x.status} · ${x.slots_left} left · ${x.budget}</small></div><div class="row-actions">${x.status==='open'?`<button class="btn btn-light" onclick="adminTaskAction(${x.id},'pause')">Pause</button>`:x.status==='paused'?`<button class="btn btn-light" onclick="adminTaskAction(${x.id},'resume')">Resume</button>`:''}${x.status!=='closed'?`<button class="btn btn-light" onclick="adminTaskAction(${x.id},'close')">Close</button>`:''}</div></div>`).join('');const pending=s.submissions.filter(x=>x.status==='pending');$('#adminSubsTable').innerHTML=pending.length?pending.map(x=>`<div class="submission"><b>${escapeHtml(x.title)}</b><small>${escapeHtml(x.worker_email)} → ${escapeHtml(x.client_email)} · ${x.reward}</small><p>${escapeHtml(x.answer)}</p><div class="submission-actions"><button class="btn btn-primary" onclick="adminReview(${x.id},'approve')">Approve</button><button class="btn btn-light" onclick="adminReview(${x.id},'reject')">Reject</button></div></div>`).join(''):'<p class="empty">No pending submissions.</p>';$('#adminLedgerTable').innerHTML=l.entries.slice(0,30).map(x=>`<div class="ledger-row"><span>${escapeHtml(x.email)}</span><span class="${x.amount_cents>=0?'positive':'negative'}">${x.amount}</span><small>${escapeHtml(x.kind)} · ${escapeHtml(x.note)}</small></div>`).join('')}catch(e){console.log(e)}}
async function adminUserAction(id,action){try{await api('/api/admin/user-action',{method:'POST',body:JSON.stringify({user_id:id,action})});await loadAdmin()}catch(e){alert(e.message)}}
async function adminTaskAction(id,action){try{await api('/api/admin/task-action',{method:'POST',body:JSON.stringify({task_id:id,action})});await loadAdmin();await loadTasks()}catch(e){alert(e.message)}}
async function adminReview(id,decision){try{await api('/api/admin/review',{method:'POST',body:JSON.stringify({submission_id:id,decision})});await loadAdmin();await loadTasks()}catch(e){alert(e.message)}}

async function refreshUI(){await loadMe();updateUser();await loadTasks();const c=$('#client'),adm=$('#admin');if(user&&user.role==='client'){c.classList.remove('hidden')}else{c.classList.add('hidden')}if(user&&user.role==='admin'){adm.classList.remove('hidden');await loadAdmin()}else{adm.classList.add('hidden')}}
$('#logoutBtn').onclick=logout;$('#startBtn').onclick=()=>user&&user.role==='worker'?document.querySelector('#tasks').scrollIntoView():openAuth('register');$('#creward').addEventListener('input',updateBudget);$('#cqty').addEventListener('input',updateBudget);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadTasks(b.dataset.filter)});
(async()=>{await refreshUI()})();
