let token=localStorage.getItem('taskearn_token')||''; let user=null; let authMode='register'; let activeTask=null;
const $=s=>document.querySelector(s);
async function api(path,options={}){options.headers={...(options.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}; const r=await fetch(path,options); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Request failed'); return d;}
function openAuth(mode='register'){authMode=mode; $('#authModal').classList.remove('hidden'); renderAuth();}
function closeAuth(){$('#authModal').classList.add('hidden'); $('#authError').textContent='';}
function toggleAuth(){openAuth(authMode==='register'?'login':'register');}
function renderAuth(){const reg=authMode==='register'; $('#authEyebrow').textContent=reg?'GET STARTED':'WELCOME BACK'; $('#authTitle').textContent=reg?'Create your TaskEarn account':'Log in to TaskEarn'; $('#authHint').textContent=reg?'Choose Worker to earn or Client to post tasks.':'Use your TaskEarn account credentials.'; $('#role').style.display=reg?'block':'none'; $('#authAction').textContent=reg?'Create account':'Log in'; $('#authSwitch').textContent=reg?'Already have an account? Log in':'Need an account? Sign up';}
async function authSubmit(){try{const email=$('#email').value.trim(), password=$('#password').value; const data=await api('/api/'+(authMode==='register'?'register':'login'),{method:'POST',body:JSON.stringify({email,password,role:$('#role').value})}); token=data.token; user=data.user; localStorage.setItem('taskearn_token',token); closeAuth(); updateUser(); loadTasks(); alert('Welcome to TaskEarn, '+user.email+'!');}catch(e){$('#authError').textContent=e.message;}}
$('#authAction').onclick=authSubmit;
async function loadMe(){try{const d=await api('/api/me'); user=d.user; updateUser()}catch(e){user=null;}}
function updateUser(){ if(user) $('#balance').textContent='$'+(user.balance_cents/100).toFixed(2); else $('#balance').textContent='$0.00'; }
async function loadTasks(cat='all'){try{const d=await api('/api/tasks'+(cat==='all'?'':'?category='+cat)); const ts=d.tasks; $('#taskGrid').innerHTML=ts.map(t=>`<article class="task"><div><h3>${t.title}</h3><p>${t.description}</p><div class="task-meta"><span>${t.category} · ~${t.est_minutes} min</span><span>● ${t.taken?'Submitted':'Available'}</span></div></div><div class="reward"><b>${t.reward}</b><small>per task</small><button ${t.taken?'disabled':''} onclick='startTask(${t.id})'>${t.taken?'Done':'Start'}</button></div></article>`).join('')||'<p>No open tasks.</p>'; $('#heroTasks').innerHTML=ts.slice(0,4).map(t=>`<div class="task-mini"><div><b>${t.title}</b><small>${t.category} · ${t.est_minutes} min</small></div><strong>${t.reward}</strong></div>`).join('');}catch(e){$('#taskGrid').innerHTML='<p>Log in as a worker to start tasks.</p>';}}
async function startTask(id){if(!user){openAuth('login');return;} if(user.role!=='worker'){alert('This account is not a worker account.');return;} try{const d=await api('/api/tasks/start',{method:'POST',body:JSON.stringify({task_id:id})}); activeTask=d.task; $('#taskTitle').textContent=activeTask.title; $('#taskDescription').textContent=activeTask.description; $('#taskReward').textContent='$'+(activeTask.reward_cents/100).toFixed(2); $('#taskTime').textContent='~'+activeTask.est_minutes+' min'; $('#taskAnswer').value=''; $('#taskError').textContent=''; $('#taskModal').classList.remove('hidden');}catch(e){alert(e.message);}}
function closeTask(){$('#taskModal').classList.add('hidden');}
async function submitTask(){try{const answer=$('#taskAnswer').value.trim(); await api('/api/tasks/submit',{method:'POST',body:JSON.stringify({task_id:activeTask.id,answer})}); closeTask(); loadTasks(); alert('Submitted. Your client can now review the task.');}catch(e){$('#taskError').textContent=e.message;}}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadTasks(b.dataset.filter)});
(async()=>{await loadMe(); await loadTasks();})();
async function loadClient(){if(!user||user.role!=='client')return; const d=await api('/api/client/tasks'); $('#subs').innerHTML=d.submissions.length?d.submissions.map(s=>`<div class="submission"><b>${s.title}</b><small>${s.worker_email} · ${s.reward} · ${s.status}</small><div class="submission-actions">${s.status==='pending'?`<button class="btn btn-primary" onclick="reviewSubmission(${s.id},'approve')">Approve</button><button class="btn btn-light" onclick="reviewSubmission(${s.id},'reject')">Reject</button>`:''}</div></div>`).join(''):'<p>No submissions yet.</p>'; }
async function createClientTask(){try{await api('/api/client/tasks',{method:'POST',body:JSON.stringify({title:$('#ctitle').value,description:$('#cdesc').value,category:$('#ccat').value,reward:$('#creward').value,est_minutes:$('#ctime').value})}); $('#ctitle').value='';$('#cdesc').value='';$('#creward').value='';$('#clientError').textContent=''; alert('Task published.');loadTasks();loadClient();}catch(e){$('#clientError').textContent=e.message;}}
async function reviewSubmission(id,decision){try{await api('/api/client/review',{method:'POST',body:JSON.stringify({submission_id:id,decision})});loadClient();alert('Submission '+decision+'d.');}catch(e){alert(e.message);}}
const oldUpdateUser=updateUser; updateUser=function(){oldUpdateUser(); const panel=$('#client'); if(panel){if(user&&user.role==='client'){panel.classList.remove('hidden');panel.style.display='block';loadClient();}else{panel.classList.add('hidden');panel.style.display='none';}}}
